### ISSUE TITLE
Where is "position: sticky"?

### ISSUE THREAD

**Issue by splincode** [vasanthk/css-refresher-notes#5]

**Comment by vasanthk** [comment]
@splincode My knowledge on the topic is insufficient.
I believe it is still unsupported by many [browsers](http://caniuse.com/#feat=css-sticky).
I will gladly accept a PR :)

**Comment by vasanthk** [comment]
Also, the spec is unfinished and Chrome removed it after adding it.
http://stackoverflow.com/a/26222260/1672655
